### ISSUE TITLE
Lambda function generating an error

### ISSUE THREAD

**Issue by gdelisle** [CU-CloudCollab/aws-manage-lifecycles#8]
An error seems to be occurring with the latest (Dec. 20) release. I can see it by running the "testlifecycle" test, as well as in the Cloudwatch logs whenever the event runs.

:
{
  "errorType": "Runtime.ImportModuleError",
  "errorMessage": "Error: Cannot find module 'xmlbuilder'",
  "trace": [
    "Runtime.ImportModuleError: Error: Cannot find module 'xmlbuilder'",
    "    at _loadUserApp (/var/runtime/UserFunction.js:100:13)",
    "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
    "    at Object.<anonymous> (/var/runtime/index.js:45:30)",
    "    at Module._compile (internal/modules/cjs/loader.js:778:30)",
    "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)",
    "    at Module.load (internal/modules/cjs/loader.js:653:32)",
    "    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)",
    "    at Function.Module._load (internal/modules/cjs/loader.js:585:3)",
    "    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)",
    "    at startup (internal/bootstrap/node.js:283:19)"
  ]
}

Here's the log:
START RequestId: a3e89561-7ad1-4f49-87e3-aaae35528fcf Version: $LATEST
2020-03-17T21:23:53.539Z	undefined	ERROR	Uncaught Exception	{"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module 'xmlbuilder'","stack":["Runtime.ImportModuleError: Error: Cannot find module 'xmlbuilder'","    at _loadUserApp (/var/runtime/UserFunction.js:100:13)","    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)","    at Object.<anonymous> (/var/runtime/index.js:45:30)","    at Module._compile (internal/modules/cjs/loader.js:778:30)","    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)","    at Module.load (internal/modules/cjs/loader.js:653:32)","    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)","    at Function.Module._load (internal/modules/cjs/loader.js:585:3)","    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)","    at startup (internal/bootstrap/node.js:283:19)"]}
END RequestId: a3e89561-7ad1-4f49-87e3-aaae35528fcf
REPORT RequestId: a3e89561-7ad1-4f49-87e3-aaae35528fcf	Duration: 2719.25 ms	Billed Duration: 2800 ms	Memory Size: 128 MB	Max Memory Used: 22 MB	
Unknown application error occurred
Runtime.ImportModuleError

**Comment by paul-e-allen** [comment]
Can you confirm that your Lambda function is using the Node.js 10.x runtime? I've looked at our two deployments and we aren't seeing any errors like this.

**Comment by gdelisle** [comment]
I found my problem. When I updated the CloudFormation template, it carried in the old parameter values including the key to the zip file, which was (for me) lambda-code.v1_1.zip. Updating that parameter and reapplying the template resolved the error, and the test ran successfully. Closing this issue and thanks for your help.
